import type { Metadata } from "next";
import { Inter, Special_Elite } from "next/font/google";
import "./globals.css";
import { Oswald } from "next/font/google";

const elite = Special_Elite({ 
  subsets: ["latin"],
  weight:["400"],
  variable: '--font-elite'});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={elite.className}>{children}</body>
    </html>
  );
}
